image: docker:git

cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq
# Install composer
- curl -sS https://getcomposer.org/installer | php
# Install all project dependencies
- php composer.phar install

test:5.6:
  image: php:5.6
  script:
  - phpcs --standard=Joomla --encoding=utf-8 --report=summary --extensions=php -p